<?php
require_once __DIR__ . '/../../lang/translate.php';

function export_label($key) {
    static $labels = [
        "es" => [
            "analytics_report" => "Reporte de analitica global",
            "answers" => "Respuestas",
            "average_difficulty" => "Dificultad promedio",
            "average_response_time" => "Tiempo promedio",
            "category" => "Categoria",
            "code" => "Codigo",
            "correct" => "Correctas",
            "correct_answers" => "Respuestas correctas",
            "correct_answer" => "Respuesta correcta",
            "date" => "Fecha",
            "difficulty" => "Dificultad",
            "failure_rate" => "Tasa de error",
            "explanation" => "Explicacion",
            "generated_at" => "Generado el",
            "downloaded_by" => "Descargado por",
            "report_type" => "Tipo de reporte",
            "report_version" => "Version del reporte",
            "report_source" => "Fuente",
            "system_source" => "Serious Game: Colesterol",
            "game_result_report" => "Reporte de partida",
            "result_id" => "ID de resultado",
            "game_mode" => "Modo de juego",
            "global_precision" => "Precision global",
            "incorrect" => "Incorrectas",
            "incorrect_answers" => "Respuestas incorrectas",
            "max_difficulty" => "Dificultad maxima",
            "mistakes" => "Errores",
            "most_failed_questions" => "Preguntas con mas errores",
            "options" => "Opciones",
            "performance_by_category" => "Rendimiento por categoria",
            "player" => "Jugador",
            "players" => "Jugadores",
            "player_report" => "Reporte de perfil del jugador",
            "points" => "Puntos",
            "precision" => "Precision",
            "question" => "Pregunta",
            "question_id" => "ID de pregunta",
            "questions" => "Preguntas",
            "ranking" => "Ranking",
            "recent_mistakes" => "Errores recientes",
            "report_footer" => "Reporte generado por Serious Game: Colesterol.",
            "room" => "Sala",
            "room_code" => "Codigo de sala",
            "room_name" => "Nombre de sala",
            "room_report" => "Reporte de sala",
            "rooms" => "Salas",
            "score" => "Puntaje",
            "selected" => "Seleccionada",
            "selected_answer" => "Respuesta seleccionada",
            "status" => "Estado",
            "summary" => "Resumen",
            "time" => "Tiempo",
            "top_players" => "Mejores jugadores",
            "top_rooms" => "Mejores salas",
            "total" => "Total",
            "total_answers" => "Respuestas totales",
            "total_games" => "Partidas totales",
            "total_players" => "Jugadores totales",
            "total_points" => "Puntos totales",
            "total_questions" => "Preguntas totales",
            "total_rooms" => "Salas totales",
            "total_users" => "Usuarios totales",
            "users" => "Usuarios",
        ],
        "en" => [
            "analytics_report" => "Global analytics report",
            "answers" => "Answers",
            "average_difficulty" => "Average difficulty",
            "average_response_time" => "Average response time",
            "category" => "Category",
            "code" => "Code",
            "correct" => "Correct",
            "correct_answers" => "Correct answers",
            "correct_answer" => "Correct answer",
            "date" => "Date",
            "difficulty" => "Difficulty",
            "failure_rate" => "Failure rate",
            "explanation" => "Explanation",
            "generated_at" => "Generated at",
            "downloaded_by" => "Downloaded by",
            "report_type" => "Report type",
            "report_version" => "Report version",
            "report_source" => "Source",
            "system_source" => "Serious Game: Cholesterol",
            "game_result_report" => "Game result report",
            "result_id" => "Result ID",
            "game_mode" => "Game mode",
            "global_precision" => "Global precision",
            "incorrect" => "Incorrect",
            "incorrect_answers" => "Incorrect answers",
            "max_difficulty" => "Max difficulty",
            "mistakes" => "Mistakes",
            "most_failed_questions" => "Most failed questions",
            "options" => "Options",
            "performance_by_category" => "Performance by category",
            "player" => "Player",
            "players" => "Players",
            "player_report" => "Player profile report",
            "points" => "Points",
            "precision" => "Precision",
            "question" => "Question",
            "question_id" => "Question ID",
            "questions" => "Questions",
            "ranking" => "Ranking",
            "recent_mistakes" => "Recent mistakes",
            "report_footer" => "Report generated by Serious Game: Cholesterol.",
            "room" => "Room",
            "room_code" => "Room code",
            "room_name" => "Room name",
            "room_report" => "Room report",
            "rooms" => "Rooms",
            "score" => "Score",
            "selected" => "Selected",
            "selected_answer" => "Selected answer",
            "status" => "Status",
            "summary" => "Summary",
            "time" => "Time",
            "top_players" => "Top players",
            "top_rooms" => "Top rooms",
            "total" => "Total",
            "total_answers" => "Total answers",
            "total_games" => "Total games",
            "total_players" => "Total players",
            "total_points" => "Total points",
            "total_questions" => "Total questions",
            "total_rooms" => "Total rooms",
            "total_users" => "Total users",
            "users" => "Users",
        ],
    ];

    $lang = current_lang() === "en" ? "en" : "es";
    return $labels[$lang][$key] ?? $labels["es"][$key] ?? $key;
}

function export_csv_open($filename) {
    header("Content-Type: text/csv; charset=utf-8");
    header("Content-Disposition: attachment; filename=\"$filename\"");

    $output = fopen("php://output", "w");
    fwrite($output, "\xEF\xBB\xBF");
    fwrite($output, "sep=,\r\n");

    return $output;
}

function export_csv_title($output, $title) {
    export_csv_write($output, [$title]);
    export_csv_write($output, [export_label("generated_at"), date("Y-m-d H:i:s")]);
    export_csv_write($output, []);
}

function export_csv_section($output, $title) {
    export_csv_write($output, []);
    export_csv_write($output, [$title]);
}

function export_csv_safe_cell($value) {
    if (!is_string($value)) {
        return $value;
    }

    $trimmed = ltrim($value);

    if ($trimmed !== "" && in_array($trimmed[0], ["=", "+", "-", "@"], true)) {
        return "'" . $value;
    }

    return $value;
}

function export_csv_write($output, array $row): void {
    fputcsv($output, array_map("export_csv_safe_cell", $row));
}

function export_logo_data_uri() {
    $logoPath = __DIR__ . '/../../assets/icons/icon.svg';

    if (!file_exists($logoPath)) {
        return "";
    }

    return "data:image/svg+xml;base64," . base64_encode(file_get_contents($logoPath));
}

function export_pdf_logo_html() {
    $logo = export_logo_data_uri();

    if ($logo === "") {
        return "";
    }

    return "<img class='report-logo' src='" . htmlspecialchars($logo, ENT_QUOTES, "UTF-8") . "' alt='Serious Game: Colesterol'>";
}

function export_report_version() {
    return "1.0";
}

function export_pdf_trace_html($reportType, array $extraRows = []) {
    $downloadedBy = trim((string)($_SESSION["user_name"] ?? ""));
    $email = trim((string)($_SESSION["user_email"] ?? ""));
    $role = trim((string)($_SESSION["user_role"] ?? ""));

    if ($downloadedBy === "") {
        $downloadedBy = "Sistema";
    }

    if ($email !== "") {
        $downloadedBy .= " <" . $email . ">";
    }

    if ($role !== "") {
        $downloadedBy .= " (" . $role . ")";
    }

    $rows = [
        export_label("generated_at") => date("Y-m-d H:i:s"),
        export_label("downloaded_by") => $downloadedBy,
        export_label("report_type") => $reportType,
        export_label("report_version") => export_report_version(),
        export_label("report_source") => export_label("system_source")
    ];

    foreach ($extraRows as $label => $value) {
        $rows[$label] = (string)$value;
    }

    $html = "<div class='meta trace-meta'>";

    foreach ($rows as $label => $value) {
        $safeLabel = htmlspecialchars((string)$label, ENT_QUOTES, "UTF-8");
        $safeValue = htmlspecialchars((string)$value, ENT_QUOTES, "UTF-8");
        $html .= "{$safeLabel}: <strong>{$safeValue}</strong><br>";
    }

    $html .= "</div>";

    return $html;
}
?>
