<?php
require_once __DIR__ . '/../lang/translate.php';
require_once __DIR__ . '/../includes/auth.php';

require_login();

$styleVersion = filemtime(__DIR__ . '/../assets/css/style.css');
$soundVersion = filemtime(__DIR__ . '/../assets/js/sound_fx.js');
$themeVersion = filemtime(__DIR__ . '/../assets/js/theme.js');

header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Pragma: no-cache");
?>
<!DOCTYPE html>
<html lang="<?php echo current_lang(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo current_lang() === "en" ? "Sound test" : "Prueba de sonidos"; ?></title>
    <link rel="stylesheet" href="<?php echo asset_path('css/style.css'); ?>?m=<?php echo $styleVersion; ?>">
    <link rel="icon" type="image/svg+xml" href="<?php echo asset_path('icons/icon.svg'); ?>">
</head>
<body>
<div class="game-container admin-container sound-test-container">
    <div class="top-actions">
        <div class="language-pill">
            <a href="?lang=es">ES</a>
            <span>|</span>
            <a href="?lang=en">EN</a>
        </div>

        <a href="<?php echo app_path('pages/admin_dashboard.php'); ?>" class="logout-btn secondary-btn">
            <?php echo current_lang() === "en" ? "Back" : "Volver"; ?>
        </a>
    </div>

    <h1><?php echo current_lang() === "en" ? "Sound test" : "Prueba de sonidos"; ?></h1>
    <p class="page-intro">
        <?php echo current_lang() === "en"
            ? "These effects are generated by code with Web Audio, so they are original and license-free."
            : "Estos efectos se generan por código con Web Audio, así que son originales y libres de licencia."; ?>
    </p>

    <section class="admin-section">
        <div class="sound-test-grid">
            <button type="button" class="primary-btn" data-sound="select">Seleccionar</button>
            <button type="button" class="primary-btn" data-sound="correct">Correcta</button>
            <button type="button" class="primary-btn" data-sound="incorrect">Incorrecta</button>
            <button type="button" class="primary-btn" data-sound="gameOver">Sin vidas</button>
            <button type="button" class="primary-btn" data-sound="timeout">Tiempo agotado</button>
            <button type="button" class="primary-btn" data-sound="continue">Continuar</button>
            <button type="button" class="primary-btn" data-sound="finish">Fin de juego</button>
            <button type="button" class="primary-btn" data-sound="badge">Badge</button>
            <button type="button" class="primary-btn" data-sound="click">Click</button>
            <button type="button" class="primary-btn" id="timer-sound-demo">Tiempo 10s</button>
            <button type="button" class="primary-btn" id="confetti-demo">Confeti</button>
        </div>
    </section>
</div>

<script src="<?php echo asset_path('js/sound_fx.js'); ?>?m=<?php echo $soundVersion; ?>"></script>
<script>
const APP_BASE_PATH = "<?php echo htmlspecialchars(app_base_path(), ENT_QUOTES, 'UTF-8'); ?>";
const appUrl = path => `${APP_BASE_PATH}/${String(path || "").replace(/^\//, "")}`;
document.querySelectorAll("[data-sound]").forEach(button => {
    button.addEventListener("click", () => {
        window.GameSounds?.setEnabled(true);
        window.GameSounds?.play(button.dataset.sound);
    });
});

document.getElementById("timer-sound-demo").addEventListener("click", event => {
    window.GameSounds?.setEnabled(true);
    let remaining = 10;
    event.currentTarget.disabled = true;
    event.currentTarget.textContent = "Tiempo: 10";

    const interval = setInterval(() => {
        remaining--;
        window.GameSounds?.timerTick(remaining, 10);
        event.currentTarget.textContent = `Tiempo: ${remaining}`;

        if (remaining <= 0) {
            clearInterval(interval);
            window.GameSounds?.play("timeout");
            event.currentTarget.disabled = false;
            event.currentTarget.textContent = "Tiempo 10s";
        }
    }, 1000);
});

document.getElementById("confetti-demo").addEventListener("click", () => {
    window.GameSounds?.setEnabled(true);
    window.GameSounds?.play("finish");
    window.GameSounds?.confetti({ count: 120, mode: "side" });
});
</script>
<script src="<?php echo asset_path('js/theme.js'); ?>?m=<?php echo $themeVersion; ?>"></script>
</body>
</html>
